version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "weekly"
      time: "00:00"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      timezone: "Asia/Tokyo"
      interval: "weekly"
      time: "00:00"
